presenters: ui and views
- ui: apppartials -> decorators, use @get, doc, lint
- views/controllers: rename @presenter -> @get
 - presenter: add UserDashboard, use in view
- ui: 'metadata-box'
- introduce ui-partials, move polystuff there. partials are app-specific UI elements that expect a 'presenter' object
- polybox: add meta to thumbnail (CSS hack)
- show: containers, overview, polybox with subheadings
- fix alerts, user_menu, page-header
- app: collection: show: @presenter -> polybox
- assets: add dev_todo.png
- lint and cleanup

diff --git a/dev/check b/dev/check
--- a/dev/check
+++ b/dev/check
@@ -1,18 +1,23 @@
 #!/bin/sh
-set -e
+RES=1
 
 printf 'rubocop... '
-bundle exec rubocop .
-echo OK
+bundle exec rubocop . \
+  && RES=0
 
-printf 'flog... '
-bundle exec cider-ci_flog app/
+echo ''; printf 'flog... '
+bundle exec cider-ci_flog app/ \
+  || RES=1
 
-printf 'flay... '
-bundle exec cider-ci_flay app/
+echo ''; printf 'flay... '
+bundle exec cider-ci_flay app/ \
+  || RES=1
 
-printf 'haml-lint... '
-./dev/test/haml-lint >/dev/null # tmp refactor
-echo OK
+echo ''; printf 'haml-lint... '
+# tmp refactor
+./dev/test/haml-lint \
+  && echo OK || RES=1
 
-echo;echo 'yay \o/'
+echo ''
+test $RES = 0 && echo 'yay \o/' || echo 'FAIL m('
+exit $RES
